elsif essette_sub_class == "Cardiology (HH)" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "BE"
elsif essette_sub_class == "Cardiology (HH)" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Clinical Trial" && status == "Approved" && status_reason == "Clinical Trial"
  ex_code = "A6"
elsif essette_sub_class == "Clinical Trial" && status == "Approved" && status_reason == "Administration Denial"
  ex_code = "9A"
elsif essette_sub_class == "Clinical Trial" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A6"
elsif essette_sub_class == "Clinical Trial" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A6"
elsif essette_sub_class == "DME" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "BF"
elsif essette_sub_class == "DME" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "BF"
elsif essette_sub_class == "DME" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "BF"
elsif essette_sub_class == "DME" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "9A"
elsif essette_sub_class == "Genetic Testing" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Genetic Testing" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "OP Behavioral Health" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "OP Substance Abuse" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Out of Network Services" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Approved" && status_reason == "Service Not Available In-Network"
  ex_code = "A7"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Part B Therapy" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Predetermination Request" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Approved" && status_reason == "Medical Criteria Met"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "9A"
elsif essette_sub_class == "Transplant Eval" && status == "Approved" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Approved" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Transplant Eval" && status == "Approved" && status_reason == "Secondary Only"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Approved" && status_reason == "With Additional Info"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Approved" && status_reason == "Services Not Available In-Network"
  ex_code = "A7"
elsif essette_sub_class == "Transplant Eval" && status == "Approved" && status_reason == "Transplant Evaluation"
  ex_code = "AB"
elsif essette_sub_class == "Cardiology (HH)" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Clinical Trial" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Clinical Trial" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Genetic Testing" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "OP Behavioral Health" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "OP Substance Abuse" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Out of Network Services" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Part B Therapy" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Predetermination Request" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Radiology (HH)" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Transplant Eval" && status == "Denied" && status_reason == "PPO-In-Network Rate"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Denied" && status_reason == "PPO-Out-of-Network Rate"
  ex_code = "9A"
elsif essette_sub_class == "Cardiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Clincal Trial" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Clincal Trial" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Clincal Trial" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Clincal Trial" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "MAXIMUS"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "MediGold Appeal"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Overturned on Appeal (Reopen)" && status_reason == "ALJ"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Overturned on Appeal (Reopen)" && status_reason == "KEPRO"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Cardiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Clinical Trial" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Clinical Trial" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Clinical Trial" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "DME" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "DME" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Genetic Testing" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Genetic Testing" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "OP Behavioral Health" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "OP Behavioral Health" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "OP Substance Abuse" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "OP Substance Abuse" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Out of Network Services" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Out of Network Services" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Part B Therapy" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Part B Therapy" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Predetermination Request" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Predetermination Request" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Radiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Radiology (HH)" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Transplant Eval" && status == "Overturned on Appeal (Reopen)" && status_reason == "Exceeds Quantity or Frequency Limits"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Covered by Medicare"
  ex_code = "9A"
elsif essette_sub_class == "Transplant Eval" && status == "Overturned on Appeal (Reopen)" && status_reason == "Portion of Request Not Medically Necessary"
  ex_code = "9A"
elsif essette_sub_class == "Cardiology (HH)" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Cardiology (HH)" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Clinical Trial" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Clinical Trial" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Clinical Trial" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Clinical Trial" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "DME" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Genetic Testing" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Geneteic Testing" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "OP Behavioral Health" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "OP Substance Abuse" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Out of Network Services" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Part B Therapy" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Predetermination Request" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Radiology (HH)" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Post Approval Change" && status_reason == "Withdrawn"
  ex_code = "BL"
elsif essette_sub_class == "Transplant Eval" && status == "Post Approval Change" && status_reason == "Date Change"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Post Approval Change" && status_reason == "Provider Change"
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Post Approval Change" && status_reason == "Procedure Change"
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Clinical Trial" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "DME" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Genetic Testing" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Integrated Oncology" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "OP Behavioral Health" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "OP Substance Abuse" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Out of Network Services" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Part B Therapy" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Predetermination Request" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Radiology (HH)" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Transplant Eval" && status == "Reopen Approved" && status_reason == ""
  ex_code = "A1"
elsif essette_sub_class == "Cardiology (HH)" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Cardiology (HH)" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Cardiology (HH)" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Cardiology (HH)" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Cardiology (HH)" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Clinical Trial" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Clinical Trial" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Clinical Trial" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Clinical Trial" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Clinical Trial" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "DME" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "DME" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "DME" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "DME" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "DME" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Genetic Testing" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Genetic Testing" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Genetic Testing" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Genetic Testing" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Genetic Testing" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Hyperbaric Oxygen" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Integrated Oncology (HH)" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "OP Behavioral Health" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "OP Behavioral Health" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "OP Behavioral Health" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "OP Behavioral Health" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "OP Behavioral Health" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "OP Substance Abuse" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "OP Substance Abuse" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "OP Substance Abuse" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "OP Substance Abuse" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "OP Substance Abuse" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Out of Network Services" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Out of Network Services" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Out of Network Services" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Out of Network Services" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Out of Network Services" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Outpatient Surgery/Procedure" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Part B Therapy" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Part B Therapy" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Part B Therapy" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Part B Therapy" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Part B Therapy" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Predetermination Request" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Predetermination Request" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Predetermination Request" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Predetermination Request" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Predetermination Request" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Radiology (HH)" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Radiology (HH)" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Radiology (HH)" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Radiology (HH)" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Radiology (HH)" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
elsif essette_sub_class == "Transplant Eval" && status == "Reopen Denied" && status_reason == "Services Available In-Network"
  ex_code = "BC"
elsif essette_sub_class == "Transplant Eval" && status == "Reopen Denied" && status_reason == "Not a Covered Benefit (PA)"
  ex_code = "WL"
elsif essette_sub_class == "Transplant Eval" && status == "Reopen Denied" && status_reason == "Not Medically Necessary"
  ex_code = "WR"
elsif essette_sub_class == "Transplant Eval" && status == "Reopen Denied" && status_reason == "Requested Medical Documentation Not Received"
  ex_code = "WS"
elsif essette_sub_class == "Transplant Eval" && status == "Reopen Denied" && status_reason == "Requested Services Considered Experimental"
  ex_code = "94"
